// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdkadtjpiyqxobdjugki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNka2FkdGpwaXlxeG9iZGp1Z2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDUzNTUsImV4cCI6MjA2NjQ4MTM1NX0.wWhpe_MjSUTc5V4jhS3suWa0JwQPW2XwJUMn9td8FcE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);